spring:
  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

  resources:
    static-locations: classpath:/static/
    add-mappings: true
    chain:
      cache: true
      enabled: true
      html-application-cache: true
      compressed: true
    cache:
      period: 3600

  datasource:
    # druid
    #url: jdbc:mysql://rm-2ze8a0jt9x45r19k7o.mysql.rds.aliyuncs.com:3306/heat_db?noAccessToProcedureBodies=true&characterEncoding=utf8
    url : jdbc:mysql://123.56.138.35:3306/miaosha?noAccessToProcedureBodies=true&characterEncoding=utf8
    username: root
    password: Hlxt@316
    filters: stat
    maxActive: 1000
    initialSize: 500
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 139.199.127.63
    port: 5672
    username: luan
    password: luan
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
  redis:
    #139.199.127.63
    host: 123.56.138.35
    port: 6379
    password: LuanMingLM111
    jedis:
      pool:
        max-idle: 500
        max-wait: 500
        max-active: 1000
    timeout: 200
mybatis:
  type-aliases-package: com.lanme.miaosha.model
  mapper-locations: classpath:com/lanme/miaosha/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

#    url: jdbc:mysql://139.199.127.63:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123